apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-zjgtvqux
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-zjgtvqux:8ffc53dac9b91684f23bb270bc98661ebfe6bd8d@sha256:751fa1e163cde136e698959399a8afacd106010f30781a9951767cfcb72ba9b4
          name: container-image
